export const AUTH_URLS = {
  USERS_AUTHENTICATE: "/auth/token",
}

export const AUTH_ACTION = {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT: "USERS_LOGOUT",
}
